name: Build Website - PR

on:
  pull_request: 
    branches: ["main"]

  workflow_dispatch:

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.BUILD_PATH }}
      - name: Build with Astro
        run: |
          pnpm astro build
        working-directory: ${{ env.BUILD_PATH }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: dist/
