name: Build & Deploy website

on:
  push:
    branches: ["main"]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.BUILD_PATH }}
      - name: Build with Astro
        run: |
          pnpm astro build
        working-directory: ${{ env.BUILD_PATH }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Cloudflare Pages GitHub Action
        uses: cloudflare/pages-action@v1.5.0
        with:
          # Cloudflare API Token
          apiToken: ${{secrets.CF_PAGES_PAT}}
          # Cloudflare Account ID
          accountId: ${{secrets.CF_ACCOUNT_ID}}
          # The name of the Pages project to upload to
          projectName: strongtownstest
          # The directory of static assets to upload
          directory: /dist
          # GitHub Token
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
