name: Lint Markdown files

on:
  pull_request: 
    branches: ["main"]

  workflow_dispatch:


jobs:
  build:
    name: Lint Markdown files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'